apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: semantic
webhooks:
  - name: semantic.default.svc.cluster.local
    rules:
      - operations:
          - "CREATE"
        apiGroups:
          - ""
        apiVersions:
          - "v1"
        resources:
          - "pods"
    failurePolicy: Ignore
    clientConfig:
      service:
        path: "/mutate"
        port: 443
        name: semantic
        namespace: default
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01USXhPVEl5TlRVME5sb1hEVE13TVRJeE56SXlOVFUwTmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXdNCnJNaUZ0cGkvSUpJVjh6K2pEL011YmRnSFgxd2U0azhnTnJvbkdTajVaWG1hUWRWNkFMRzJkZVB5SERjUHM5TzAKMEtiTWRLZUd2UXhHWDJteGwxZVp3M0VxVTRHUG44WXUrQTd0UTJ5RDEvK2hLRHVNejNVU0ZNUDJFUVdId3VzRQpVcEQwVUVpT2EwSzcvUUdLRmlmKzRSNXdTaDZBdXYxejV6USszZUx3ZE5UQ1BLdFVyVUxrWlZoK2dQSkthR1dwCjEwZTZDWEg3eVduUHpzMERDeExkeWFQMmo4V2QrOEgrb2duS2NnK3dPVzlBR0NGdHNLRHJISW9tMHdibnB2MFEKL0J4TG9zdXBXQ1VYd1l6MktYN1h5OHhpa3A0MTFRaFVlbGFibFN1eHFheGEweWpQNzBLNXFlN2NTd3NURVg0WApjZGx6MHFNajhNQnlRa3VqZmhrQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJTDFiQ1lOclhUTVNMRElsZG9yNXJUVEs0YVpNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCa1h6Z0pGb3BXTnpyckp4VjEwYWRNcUxJZnFDanZWWS82b3pRSVBXMXVyM2NQUzF4VQovR1U5RzNqYmZ5RHcyQmo2QVY3c21heW5WL0QxQkpoM2p2Q3Z5TGdDM252cmROWGZVTXlQVC9KU2lKSHRYakVUCjg3Y3I5L1loLzZnWElWcDU4aUxRYllDWEJlSk15Z3hHUG1lOHRlUWJpdGhTNVJuU3JBMUNXUGQ4OVJrK3AyVXIKazJUTkVxYUIwNHZhS0wyTmliKy9VbXZLUUx0SEk5cDdxVzF3RENuL293UElTL1VncS85bXVWa2ZTOEJLMDRPdgp5ZjhKeHBuRDM1dXQ1WFMrM2JUdllhdEw0ZndxZDR5SmxmYmd3bTQySGZyakxwSUtKelQwcmxOS1F6RTI5NzhZCmdHaEhYSCt1K2VjalAzYjlmR2lDV00rOHV0YVNWVlRPZlpRQQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    sideEffects: None
    admissionReviewVersions:
      - "v1"
