apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: semantic.default
spec:
  groups:
    - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQllqQ0NBUWdDQVFBd1VERVZNQk1HQTFVRUNoTU1jM2x6ZEdWdE9tNXZaR1Z6TVRjd05RWURWUVFERXk1egplWE4wWlcwNmJtOWtaVHB6WlcxaGJuUnBZeTVrWldaaGRXeDBMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNNRmt3CkV3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFZzRzS0JUZS90T3E1MlRVTkRPT2NJblZ4U0RrL3hJVFEKUEdsRU5zTXQ4bSt5UDRqakIrbFFwYW9QbmM0TEsvRTdUMlg4Q0hCR1BiUkVrbm0xbXFSWG02QldNRlFHQ1NxRwpTSWIzRFFFSkRqRkhNRVV3UXdZRFZSMFJCRHd3T29JVWMyVnRZVzUwYVdNdVpHVm1ZWFZzZEM1emRtT0NJbk5sCmJXRnVkR2xqTG1SbFptRjFiSFF1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3d3Q2dZSUtvWkl6ajBFQXdJRFNBQXcKUlFJZ1pXNFNkUU5QbXdRc0FpaTRpL0V4dldLdFVPcEFFV05STzhZZytRU3FBcWNDSVFDdGRuOG1iQmIvZ0FPNgorQkdqTUZhTGhvOVVZeTM5YnRpOWJZenZtQll4dXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: kubernetes.io/kubelet-serving
  usages:
    - server auth
    - digital signature
    - key encipherment
