apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: kubernetes-semantic-image-controller.default
spec:
  groups:
    - system:authenticated
  request: <csr>
  signerName: kubernetes.io/kubelet-serving
  usages:
    - server auth
    - digital signature
    - key encipherment
