apiVersion: apps/v1
kind: Deployment
metadata:
  name: semantic
spec:
  selector:
    matchLabels:
      app: semantic
  template:
    metadata:
      labels:
        app: semantic
    spec:
      volumes:
        - name: certs
          secret:
            secretName: semantic
      containers:
        - name: semantic
          image: rawkode/kubernetes-semantic-version:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: certs
              mountPath: /certs
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 443
---
apiVersion: v1
kind: Secret
metadata:
  name: semantic
type: Opaque
data:
  webhook-key.pem: <webhook-key>
  webhook.crt: <webhook-cert>
---
apiVersion: v1
kind: Service
metadata:
  name: semantic
spec:
  selector:
    app: semantic
  ports:
    - port: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug
spec:
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      labels:
        app: debug
    spec:
      containers:
        - name: debug
          image: "nginx:>= 1.16, <= 1.18"
          command:
            - sleep
          args:
            - +Inf
